### PR TITLE
Overall improvements and support for almost all enchantments

### LINKED ISSUE #5: Further Config
hello, Just wondering if you could enable the possibility to enter our own enchantments into the config file for all the other vanilla enchantments. I tried adding my own based on the raw names of the enchantments and it did not work. Thank you!

### PR DESCRIPTION
**Pull request by Cam396**
This adds most enchantments in minecraft to sharpness 6. This took way too long lol.

### CODE REVIEW

**Comment by mastery3** [comment]
Converting to draft as there are some changes I need to make before merging.

**Comment by mastery3** [comment]
Merging this pull request into the main branch. A new release should be available soon.

**Comment by Cam396** [comment]
Thank you for changing those things and the reason I didn't put default values is I actually made this for me and my friends' server lol. could you possibly credit me for it though?

**Comment by Cam396** [comment]
Also the i didn't add the single level enchants because you would have to code for scaling support for those enchants. i might be able to help with that when I have time

**Comment by mastery3** [comment]
> could you possibly credit me for it though?

Done. Check the Modrinth changelog.

As for the scaling support, I'm probably gonna put it later after the 1.21 support.

**Comment by Cam396** [comment]
Thank you

**Pull request merged**
